Repository openshift/kubernetes-nmstate, pull requests merged in 2021-09, with the labels that each got.

#201 Bug 1987136: Declare supported arches in CSV
  manifests/4.7/kubernetes-nmstate-operator.v4.7.0.clusterserviceversion.yaml
  manifests/4.8/kubernetes-nmstate-operator.v4.8.0.clusterserviceversion.yaml
  manifests/4.9/kubernetes-nmstate-operator.v4.9.0.clusterserviceversion.yaml
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#207 Bug 1995471: Fix skip range 4.8
  manifests/4.7/kubernetes-nmstate-operator.v4.7.0.clusterserviceversion.yaml
  manifests/4.8/kubernetes-nmstate-operator.v4.8.0.clusterserviceversion.yaml
  manifests/art.yaml
Labels: kind/bug, approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#210 Sync Dockerfile.openshift with u/s
  build/Dockerfile.openshift
Labels: approved, lgtm

#208 Bug 1995506: Fix olm.skipRange substitution 4.7
  manifests/4.7/kubernetes-nmstate-operator.v4.7.0.clusterserviceversion.yaml
  manifests/art.yaml
Labels: kind/bug, approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high
