Repository openshift/kubernetes-nmstate, pull requests merged in 2021-12, with the labels that each got.

#235 Bug 2027793: [release-4.7] Remove serviceaccount manifest
  bundle/manifests/nmstate-operator_v1_serviceaccount.yaml
  manifests/4.7/nmstate-operator_v1_serviceaccount.yaml
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#238 Upstream: <carry>: Fix JSON error in initialization resource
  manifests/4.10/kubernetes-nmstate-operator.v4.10.0.clusterserviceversion.yaml
Labels: kind/bug, approved, lgtm

#237 Add ppc64le and s390x to 4.10 CSV
  hack/install-go.sh
  manifests/4.10/kubernetes-nmstate-operator.v4.10.0.clusterserviceversion.yaml
Labels: approved, lgtm

#240 Switch to dnf in Openshift handler image
  build/Dockerfile.openshift
Labels: kind/bug, approved, lgtm

#234 UPSTREAM: <carry>: Add disconnected annotation for OperatorHub
  manifests/4.10/kubernetes-nmstate-operator.v4.10.0.clusterserviceversion.yaml
Labels: approved, lgtm

#244 UPSTREAM: <carry>: Update OWNERS
  OWNERS
Labels: approved, lgtm

#245 UPSTREAM: <carry>: enable all archs in nmstate example CR
  manifests/4.10/kubernetes-nmstate-operator.v4.10.0.clusterserviceversion.yaml
Labels: kind/bug, approved, lgtm, ok-to-test

#246 Add ssh proxy for e2e tests when in CI
  hack/ocp-e2e-tests.sh
  hack/ssh-ci.sh
Labels: kind/bug, approved, lgtm
