Repository openshift/kubernetes-nmstate, pull requests merged in 2021-08, with the labels that each got.

#190 UPSTREAM: <carry>: Add manifests to .PHONY in Makefile
  Makefile
Labels: approved, kind/bug, lgtm, lifecycle/stale

#203 name replacement must exactly match string in CSV
  manifests/art.yaml
Labels: approved, lgtm

#205 name replacement must exactly match string in CSV
  manifests/art.yaml
Labels: approved, lgtm

#204 name replacement must exactly match string in CSV
  manifests/art.yaml
Labels: approved, lgtm

#206 Bug 1994991: Fix skipRange replacement
  manifests/4.7/kubernetes-nmstate-operator.v4.7.0.clusterserviceversion.yaml
  manifests/4.8/kubernetes-nmstate-operator.v4.8.0.clusterserviceversion.yaml
  manifests/4.9/kubernetes-nmstate-operator.v4.9.0.clusterserviceversion.yaml
  manifests/art.yaml
Labels: kind/bug, approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high
