Repository openshift/kubernetes-nmstate, pull requests merged in 2021-11, with the labels that each got.

#221 update naming convention
  manifests/art.yaml
Labels: kind/bug, approved, lgtm

#222 update naming convention for 4.9
  manifests/art.yaml
Labels: kind/bug, approved, lgtm

#229 Bug 2022447: Remove serviceaccount manifest
  bundle/manifests/nmstate-operator_v1_serviceaccount.yaml
  manifests/4.8/nmstate-operator_v1_serviceaccount.yaml
  manifests/4.9/nmstate-operator_v1_serviceaccount.yaml
Labels: kind/bug, approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#231 Bug 2023529: [release-4.8] Remove serviceaccount manifest
  bundle/manifests/nmstate-operator_v1_serviceaccount.yaml
  manifests/4.8/nmstate-operator_v1_serviceaccount.yaml
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#232 Skip e2e tests which are not supported on OVN
  hack/ocp-e2e-tests.sh
Labels: approved, lgtm

#233 UPSTREAM: <carry>: add arm64 to 4.10 CSV
  manifests/4.10/kubernetes-nmstate-operator.v4.10.0.clusterserviceversion.yaml
Labels: approved, lgtm
