Repository openshift/kubernetes-nmstate, pull requests merged in 2022-01, with the labels that each got.

#247 Bug 2039330: Remove initialization resource from CSV
  manifests/4.10/kubernetes-nmstate-operator.v4.10.0.clusterserviceversion.yaml
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#248 Remove initialization resource from 4.9 too
  manifests/4.9/kubernetes-nmstate-operator.v4.9.0.clusterserviceversion.yaml
Labels: kind/bug, approved, lgtm

#250 Add make target to run operator e2e tests against OCP
  Makefile
  hack/ocp-e2e-tests-handler.sh
  hack/ocp-e2e-tests-operator.sh
Labels: approved, lgtm
