Repository openshift/kubernetes-nmstate, pull requests merged in 2023-03, with the labels that each got.

#349 OCPBUGS-8441: UPSTREAM <carry>: Update goutils dependency to v1.1.1 (#1140)
  go.mod
  go.sum
  vendor/github.com/Masterminds/goutils/cryptorandomstringutils.go
  vendor/github.com/Masterminds/goutils/randomstringutils.go
  vendor/github.com/Masterminds/goutils/stringutils.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#351 Add UI Plugin manifests to Openshift Dockerfile
  build/Dockerfile.operator.openshift
Labels: kind/bug, approved, lgtm

#348 OCPBUGS-8440: UPSTREAM: <carry>: Update goutils dependency to v1.1.1
  go.mod
  go.sum
  vendor/github.com/Masterminds/goutils/cryptorandomstringutils.go
  vendor/github.com/Masterminds/goutils/randomstringutils.go
  vendor/github.com/Masterminds/goutils/stringutils.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#353 OPNET-256: Move from version-specific to stable channel
  developing-on-ocp.md
  hack/ocp-build-and-deploy-bundle.sh
  hack/ocp-bundle-common.sh
  hack/ocp-update-bundle-manifests.sh
  manifests/art.yaml
  manifests/kubernetes-nmstate-operator.package.yaml
  manifests/stable/bundle.Dockerfile
  manifests/stable/manifests/image-references
  manifests/stable/manifests/kubernetes-nmstate-operator.clusterserviceversion.yaml
  manifests/stable/manifests/nmstate.io_nmstates.yaml
  manifests/stable/metadata/annotations.yaml
Labels: approved, lgtm, jira/valid-reference

#361 OCPBUGS-10737: go.mod: update mongodb-driver to 1.11.2 (#1158)
  go.mod
  go.sum
  vendor/golang.org/x/crypto/pbkdf2/pbkdf2.go
  vendor/golang.org/x/crypto/scrypt/scrypt.go
  vendor/golang.org/x/sys/unix/asm_bsd_riscv64.s
  vendor/golang.org/x/sys/unix/syscall_freebsd_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_freebsd_riscv64.go
  vendor/golang.org/x/sys/unix/zsyscall_freebsd_riscv64.go
  vendor/golang.org/x/sys/unix/zsysnum_freebsd_riscv64.go
  vendor/golang.org/x/sys/unix/ztypes_freebsd_riscv64.go
  vendor/gopkg.in/yaml.v3/decode.go
  vendor/gopkg.in/yaml.v3/parserc.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#363 [release-4.13] Jira OCPBUGS-10955: Probes: choose the default gw from the main routing table (#1153)
  pkg/probe/probes.go
  pkg/probe/probes_test.go
  test/e2e/handler/rollback_test.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference
