Repository openshift/kubernetes-nmstate, pull requests merged in 2023-05, with the labels that each got.

#376 OCPBUGS-12970: Drop machine-config workaround from e2e tests
  hack/ocp-e2e-tests-handler.sh
  test/e2e/machineconfigs.yaml
Labels: approved, lgtm, bugzilla/valid-bug, jira/severity-important, jira/valid-bug, jira/valid-reference

#357 OPNET-261: Integrate the ART build of nmstate-console-plugin image in the manifests
  Makefile
  deploy/operator/operator.yaml
  hack/ocp-build-and-deploy-bundle.sh
  hack/ocp-bundle-common.sh
  hack/ocp-update-bundle-manifests.sh
  hack/render-manifests.go
  manifests/stable/manifests/image-references
  manifests/stable/manifests/kubernetes-nmstate-operator.clusterserviceversion.yaml
Labels: kind/bug, approved, lgtm, jira/valid-reference

#383 Merge main 2023 05 17 fb3e9c6d
  Makefile
  automation/check-patch.setup.sh
  automation/check-patch.unit-test.sh
  automation/publish.sh
  automation/release.sh
  build/Dockerfile
  build/Dockerfile.operator
  controllers/operator/nmstate_controller.go
  hack/build-push-container.docker.sh
  hack/build-push-container.podman.sh
  hack/qemu-user-static.sh
Labels: approved, lgtm

#382 UPSTREAM: <carry>: Lower flake attempts to 3
  hack/ocp-e2e-tests-handler.sh
  hack/ocp-e2e-tests-operator.sh
Labels: approved, lgtm
