Repository openshift/kubernetes-nmstate, pull requests merged in 2023-02, with the labels that each got.

#340 OCPBUGS-7135: Grant handler service account permissions to use privileged security context constraint on OCP/OKD
  cluster/clean.sh
  cluster/sync-operator.sh
  cmd/operator/main.go
  controllers/operator/nmstate_controller.go
  controllers/operator/nmstate_controller_test.go
  deploy/handler/role.yaml
  deploy/openshift/scc.yaml
  go.mod
  go.sum
  hack/render-manifests.go
  manifests/4.11/kubernetes-nmstate-operator.v4.11.0.clusterserviceversion.yaml
  pkg/cluster/cluster.go
  test/e2e/operator/nmstate_install_test.go
  test/e2e/operator/operator.go
  vendor/github.com/openshift/api/LICENSE
  vendor/github.com/openshift/api/security/v1/0000_03_security-openshift_01_scc.crd.yaml
  vendor/github.com/openshift/api/security/v1/consts.go
  vendor/github.com/openshift/api/security/v1/doc.go
  vendor/github.com/openshift/api/security/v1/generated.pb.go
  vendor/github.com/openshift/api/security/v1/generated.proto
  vendor/github.com/openshift/api/security/v1/legacy.go
  vendor/github.com/openshift/api/security/v1/register.go
  vendor/github.com/openshift/api/security/v1/types.go
  vendor/github.com/openshift/api/security/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/security/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#335 ocp-rebase: general improvements
  hack/ocp-rebase.sh
Labels: approved, lgtm

#345 makefile: general improvements
  Makefile
Labels: approved, lgtm

#346 OPNET-205: update manifest for 4.13
  manifests/4.13/bundle.Dockerfile
  manifests/4.13/manifests/image-references
  manifests/4.13/manifests/kubernetes-nmstate-operator.clusterserviceversion.yaml
  manifests/4.13/manifests/nmstate.io_nmstates.yaml
  manifests/4.13/metadata/annotations.yaml
  manifests/bases/kubernetes-nmstate-operator.clusterserviceversion.yaml
  manifests/kubernetes-nmstate-operator.package.yaml
Labels: approved, lgtm, jira/valid-reference
