Repository openshift/kubernetes-nmstate, pull requests merged in 2023-01, with the labels that each got.

#321 add ipv4 example to the interfaces in the alm-examples
  bundle.Dockerfile
  bundle/manifests/kubernetes-nmstate-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  deploy/examples/nmstate.io_v1_nodenetworkconfigurationpolicy_cr.yaml
  manifests/4.12/manifests/kubernetes-nmstate-operator.clusterserviceversion.yaml
Labels: kind/bug, approved, lgtm

#327 OCPBUGS-5124: Remove NNCP example from manifests
  deploy/examples/nmstate.io_v1_nodenetworkconfigurationpolicy_cr.yaml
  manifests/4.12/manifests/kubernetes-nmstate-operator.clusterserviceversion.yaml
Labels: approved, lgtm, bugzilla/valid-bug, jira/severity-critical, jira/valid-bug

#329 OCPBUGS-5124: Add empty spec to NMState CR example
  deploy/examples/nmstate.io_v1_nmstate_cr.yaml
  manifests/4.12/manifests/kubernetes-nmstate-operator.clusterserviceversion.yaml
  manifests/bases/kubernetes-nmstate-operator.clusterserviceversion.yaml
Labels: approved, lgtm, bugzilla/valid-bug, jira/severity-critical, jira/valid-bug

#331 Add mko as reviewer and approver
  OWNERS
Labels: approved, lgtm

#333 ocp-rebase: use -s in cherry-pick
  hack/ocp-rebase.sh
Labels: approved, lgtm
