Repository openshift/kubernetes-nmstate, pull requests merged in 2025-05, with the labels that each got.

#611 NO-JIRA: Add emy as reviewer in the owners file
  OWNERS
Labels: approved, lgtm, jira/valid-reference

#616 UPSTREAM<carry>: makefile: manually bring changes from #1335 upstream
  Makefile
  manifests/stable/bundle.Dockerfile
  manifests/stable/manifests/kubernetes-nmstate-operator.clusterserviceversion.yaml
  manifests/stable/metadata/annotations.yaml
Labels: approved, lgtm

#614 [release-4.19] openshift, handledr: Add workload annotation (#1323)
  api/go.mod
  bundle/manifests/kubernetes-nmstate-operator.clusterserviceversion.yaml
  deploy/handler/operator.yaml
  deploy/operator/operator.yaml
  manifests/stable/manifests/kubernetes-nmstate-operator.clusterserviceversion.yaml
  vendor/github.com/openshift/api/security/v1/Makefile
  vendor/github.com/openshift/api/security/v1/consts.go
  vendor/github.com/openshift/api/security/v1/doc.go
  vendor/github.com/openshift/api/security/v1/generated.pb.go
  vendor/github.com/openshift/api/security/v1/generated.proto
  vendor/github.com/openshift/api/security/v1/legacy.go
  vendor/github.com/openshift/api/security/v1/register.go
  vendor/github.com/openshift/api/security/v1/types.go
  vendor/github.com/openshift/api/security/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/security/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/api/security/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: kind/bug, approved, lgtm
