Repository openshift/kubernetes-nmstate, pull requests merged in 2025-08, with the labels that each got.

#646 UPSTREAM: <carry>: Hold network policy in the OLM bundle
  hack/ocp-update-bundle-manifests.sh
Labels: approved, lgtm

#651 NO-ISSUE: make target for check ocp-bundle would not indicate a change in bundle.
  Makefile
Labels: kind/bug, approved, lgtm, jira/valid-reference

#648 OCPBUGS-60452: Revert deadlock introduced by verbose output
  pkg/nmstatectl/nmstatectl.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference
