Repository openshift/kubernetes-nmstate, pull requests merged in 2025-04, with the labels that each got.

#589 [release-4.18]: operator, Continue on cleanup NotFound errors (#1302)
  controllers/operator/nmstate_controller.go
Labels: kind/bug, approved, lgtm

#591 ci: Sanitize secrets
  automation/check-patch.setup.sh
  hack/sanitized-xtrace.sh
Labels: approved, lgtm

#594 OCPBUGS-54295: e2e, operator, Check console plugin deployment
  deploy/openshift/ui-plugin/deployment.yaml
  test/e2e/operator/operator.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#599 [release-4.18] e2e, handler: Simplify vlan_filtering 0 check (#1279)
  test/e2e/handler/simple_bridge_and_bond_test.go
Labels: approved, lgtm

#600 [release-4.18] Enable debug logging of nmstate apply (#1294)
  pkg/nmstatectl/nmstatectl.go
Labels: approved, lgtm

#603 [release-4.18] adapt test to notsecret
  test/e2e/handler/metrics.go
Labels: approved, lgtm

#606 deps: fix yq version v4.35.2 regex
  hack/ocp-bundle-common.sh
Labels: kind/bug, approved, lgtm
