Repository openshift/kubernetes-nmstate, pull requests merged in 2025-02, with the labels that each got.

#536 [4.14] handler: Retry nncp status updated on error
  pkg/policyconditions/conditions.go
Labels: approved, lgtm

#563 [release-4.16] OCPBUGS-50627: Allow configuring node placement for nmstate-console-plugin
  api/v1/nmstate_types.go
  bundle/manifests/nmstate.io_nmstates.yaml
  controllers/operator/nmstate_controller.go
  deploy/crds/nmstate.io_nmstates.yaml
  deploy/openshift/ui-plugin/deployment.yaml
  manifests/stable/manifests/nmstate.io_nmstates.yaml
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#564 NO-JIRA: Fix 4.19 CSV references
  manifests/stable/manifests/image-references
  manifests/stable/manifests/kubernetes-nmstate-operator.clusterserviceversion.yaml
Labels: approved, lgtm, jira/valid-reference
